name: qpsolvers_benchmark
channels:
    - https://conda.anaconda.org/conda-forge
dependencies:
    - cvxopt
    - ecos
    - matplotlib
    - osqp
    - pandas
    - pip
    - proxsuite
    - qpoases
    - qpsolvers>=2.7.2
    - quadprog
    - scs
    - tabulate
    - pip:
        - py-cpuinfo
